# Generated by Django 4.1 on 2023-07-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='social_link',
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateField(blank=True, null=True),
        ),
    ]
