# Generated by Django 4.1 on 2023-07-10 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_social_link_alter_post_date_created'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='BanglaTag',
        ),
        migrations.CreateModel(
            name='EnglishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_tag', models.CharField(max_length=255)),
                ('post', models.ManyToManyField(to='main.post')),
            ],
        ),
    ]
