# Generated by Django 4.1 on 2023-07-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_tag_banglatag_englishtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='need_edit',
            field=models.BooleanField(default=False),
        ),
    ]
