# Generated by Django 4.1 on 2023-07-14 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_moderator_alter_post_reporter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_trending', models.BooleanField(default=False)),
                ('is_headline', models.BooleanField(default=False)),
                ('is_focus', models.BooleanField(default=False)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.post')),
            ],
        ),
    ]
